sugarcube-2:
  macros:
    numberbox:
       container: true
    # live-update.js
    live:
      name: live
    l:
      name: l
    lh:
      name: lh
    liveblock:
      name: liveblock
      container: true
    lb:
      name: lb
      container: true
    update:
      name: update
    upd:
      name: upd